apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla-1
  creationTimestamp: "2020-07-04T22:11:51Z"
  namespace: mc-server
  selfLink: /apis/apps/v1/namespaces/mc-server/deployments/mc-vanilla-1
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      containers:
      - image: gcr.io/nice-mix-249319/itzg/minecraft-server@sha256:3bba73c5d924971a7f85a16e82d9ae6a4f7a9ef09e206c19b8da54a5a63d8d2c
        name: mc-vanilla
        env:
        - name: EULA
          value: "true"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: mc-data
          mountPath: /data
      volumes:
      - name: mc-data
        emptyDir: {}
