apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla
  namespace: mc-server
  labels:
    app: mc-vanilla
spec:
  selector:
    app: mc-vanilla
  ports:
    - port: 25565
      protocol: TCP
  type: LoadBalancer